## CHATGPT CMON BRO

version: "2"
services:
  talk:
    image: coralproject/talk:7
    restart: always
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=${MONGO_URL}  # Use MONGO_URL from Railway
      - REDIS_URI=${REDIS_URL}  # Use REDIS_URL from Railway
      - SIGNING_SECRET=${SIGNING_SECRET}  # Keep using your SIGNING_SECRET

  mongo:
    image: mongo:4.2
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis:3.2
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}